apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: admin-portal
  name: admin-portal
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: admin-portal
  type: ClusterIP
status:
  loadBalancer: {}
